services:
  # Backend API Service
  - type: web
    name: sbah-family-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PAYDUNYA_MASTER_KEY
        sync: false
      - key: PAYDUNYA_PUBLIC_KEY
        sync: false
      - key: PAYDUNYA_PRIVATE_KEY
        sync: false
      - key: PAYDUNYA_TOKEN
        sync: false
      - key: PAYDUNYA_MODE
        value: test
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: APP_URL
        fromService:
          name: sbah-family-frontend
          type: web
          property: url
      - key: API_URL
        fromService:
          name: sbah-family-api
          type: web
          property: url

  # Frontend Static Site
  - type: web
    name: sbah-family-frontend
    env: static
    buildCommand: npm install
    staticPublishPath: ./sbah-app-v2
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: "no-cache"
      - path: /*.js
        name: Cache-Control
        value: "no-cache"
      - path: /*.css
        name: Cache-Control
        value: "no-cache"
      - path: /*.png
        name: Cache-Control
        value: "public, max-age=31536000"
      - path: /*.jpg
        name: Cache-Control
        value: "public, max-age=31536000"
    envVars:
      - key: NODE_VERSION
        value: 16.x
