services:
  # Backend API Service
  - type: web
    name: sbah-family-api
    env: docker
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: sbah-family-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: sbah-family-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: sbah-family-db
          property: password
    healthCheckPath: /api/v1/health
    autoDeploy: true

  # Frontend Service
  - type: web
    name: sbah-family-frontend
    env: static
    buildCommand: npm install
    staticPublishPath: ./sbah-app-v2
    envVars:
      - key: REACT_APP_API_URL
        value: https://sbah-family-api.onrender.com/api/v1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization, Accept"
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
    autoDeploy: true

databases:
  - name: sbah-family-db
    plan: free
    type: mysql
