services:
  # Service principal - Site statique
  - type: web
    name: sbah-family-app
    env: static
    buildCommand: echo "Static site, no build needed"
    staticPublishPath: ./sbah-app-v2
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: "public, max-age=86400"
      - path: /*.js
        name: Cache-Control
        value: "public, max-age=31536000"
      - path: /*.css
        name: Cache-Control
        value: "public, max-age=31536000"
      - path: /*.png
        name: Cache-Control
        value: "public, max-age=31536000"
      - path: /*.jpg
        name: Cache-Control
        value: "public, max-age=31536000"
    envVars:
      - key: NODE_VERSION
        value: 16.x

  # Service pour les fonctions serverless (webhook PayDunya)
  - type: web
    name: sbah-family-api
    env: node
    buildCommand: cd functions && npm install
    startCommand: node functions/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
