services:
  # Backend API Service
  - type: web
    name: sbah-family-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PAYDUNYA_MASTER_KEY
        sync: false
      - key: PAYDUNYA_PUBLIC_KEY
        sync: false
      - key: PAYDUNYA_PRIVATE_KEY
        sync: false
      - key: PAYDUNYA_TOKEN
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: sbah-family-data
      mountPath: /data
      sizeGB: 1

  # Frontend Service
  - type: web
    name: sbah-family-frontend
    env: static
    buildCommand: npm install
    staticPublishPath: ./sbah-app-v2
    envVars:
      - key: API_URL
        value: https://sbah-family-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization, Accept"
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
    autoDeploy: true
